ls:
  .dir: kebab-case
  .js: kebab-case
  features/step-definitions:
    .js: regex:^(.*-steps)?$
  .ts: kebab-case
  .d.ts: kebab-case
  .html: kebab-case
  .jpg : kebab-case
  .png : kebab-case
  .groovy : kebab-case
  .yml : kebab-case

ignore:
  - node_modules
  - wdio.conf.js
  - .ls-lint.yml
